version: "3.5"
networks:
  default:
    name: xagon
services:
  xagon-sequencer:
    container_name: xagon-sequencer
    image: xagon-node
    ports:
      - 9092:9091 # needed if metrics enabled
      - 6060:6060
    environment:
      - ZKEVM_NODE_STATEDB_HOST=xagon-state-db
      - ZKEVM_NODE_POOL_DB_HOST=xagon-pool-db
    volumes:
      - ./config/test.node.config.toml:/app/config.toml
      - ./config/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/xagon-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components sequencer"

  xagon-json-rpc:
    container_name: xagon-json-rpc
    image: xagon-node
    ports:
      - 8123:8123
      - 8133:8133 # needed if WebSockets enabled
      - 9091:9091 # needed if metrics enabled
    environment:
      - ZKEVM_NODE_STATEDB_HOST=xagon-state-db
      - ZKEVM_NODE_POOL_DB_HOST=xagon-pool-db
    volumes:
      - ./config/test.node.config.toml:/app/config.toml
      - ./config/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/xagon-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components rpc"

  xagon-aggregator:
    container_name: xagon-aggregator
    image: xagon-node
    ports:
      - 50081:50081
      - 9093:9091 # needed if metrics enabled
    environment:
      - ZKEVM_NODE_STATEDB_HOST=xagon-state-db
      - ZKEVM_NODE_AGGREGATOR_SENDER_ADDRESS=0xBAF25C3f0e7B21818Ed922a6e01bf25CA31dE19E
    volumes:
      - ./config/test.node.config.toml:/app/config.toml
      - ./config/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/xagon-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components aggregator"

  xagon-sync:
    container_name: xagon-sync
    image: xagon-node
    ports:
      - 9095:9091 # needed if metrics enabled
    environment:
      - ZKEVM_NODE_STATEDB_HOST=xagon-state-db
    volumes:
      - ./config/test.node.config.toml:/app/config.toml
      - ./config/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/xagon-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components synchronizer"

  xagon-state-db:
    container_name: xagon-state-db
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./config/init_prover_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=state_user
      - POSTGRES_PASSWORD=state_password
      - POSTGRES_DB=state_db
    command:
      - "postgres"
      - "-N"
      - "500"

  xagon-pool-db:
    container_name: xagon-pool-db
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=pool_user
      - POSTGRES_PASSWORD=pool_password
      - POSTGRES_DB=pool_db
    command:
      - "postgres"
      - "-N"
      - "500"

  xagon-event-db:
    container_name: xagon-event-db
    image: postgres
    ports:
      - 5435:5432
    volumes:
      - ./config/init_event_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=event_user
      - POSTGRES_PASSWORD=event_password
      - POSTGRES_DB=event_db
    command:
      - "postgres"
      - "-N"
      - "500"

  xagon-explorer-l1:
    container_name: xagon-explorer-l1
    image: hermeznetwork/zkevm-explorer:latest
    ports:
      - 4000:4000
    environment:
      - NETWORK=ETH
      - SUBNETWORK=Local Ethereum
      - COIN=ETH
      - ETHEREUM_JSONRPC_VARIANT=geth
      - ETHEREUM_JSONRPC_HTTP_URL=http://xagon-mock-l1-network:8545
      - DATABASE_URL=postgres://state_user:state_password@xagon-state-db:5432/l1_explorer_db
      - ECTO_USE_SSL=false
      - MIX_ENV=prod
    command:
      [
        "/bin/sh",
        "-c",
        "mix do ecto.create, ecto.migrate; mix phx.server"
      ]

  xagon-explorer-l2:
    container_name: xagon-explorer-l2
    image: hermeznetwork/zkevm-explorer:latest
    ports:
      - 4001:4000
    environment:
      - NETWORK=POE
      - SUBNETWORK=Polygon Hermez
      - COIN=ETH
      - ETHEREUM_JSONRPC_VARIANT=geth
      - ETHEREUM_JSONRPC_HTTP_URL=http://xagon-explorer-json-rpc:8124
      - DATABASE_URL=postgres://state_user:state_password@xagon-state-db:5432/l2_explorer_db
      - ECTO_USE_SSL=false
      - MIX_ENV=prod
      - INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=true
      - LOGO=/images/blockscout_logo.svg
      - LOGO_FOOTER=/images/blockscout_logo.svg
    command:
      [
        "/bin/sh",
        "-c",
        "mix do ecto.create, ecto.migrate; mix phx.server"
      ]

  xagon-explorer-json-rpc:
    container_name: xagon-explorer-json-rpc
    image: xagon-node
    ports:
      - 8124:8124
    environment:
      - ZKEVM_NODE_STATEDB_HOST=xagon-state-db
      - ZKEVM_NODE_POOL_DB_HOST=xagon-pool-db
      - ZKEVM_NODE_RPC_PORT=8124
      - ZKEVM_NODE_RPC_WEBSOCKETS_PORT=8134
    volumes:
      - ./config/test.node.config.toml:/app/config.toml
      - ./config/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/xagon-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components rpc --http.api eth,net,debug,xagon,txpool,web3"
  xagon-mock-l1-network:
    container_name: xagon-mock-l1-network
    image: hermeznetwork/geth-zkevm-contracts:latest
    ports:
      - 8545:8545
      - 8546:8546
    command:
      - "--http"
      - "--http.api"
      - "admin,eth,debug,miner,net,txpool,personal,web3"
      - "--http.addr"
      - "0.0.0.0"
      - "--http.corsdomain"
      - "*"
      - "--http.vhosts"
      - "*"
      - "--ws"
      - "--ws.origins"
      - "*"
      - "--ws.addr"
      - "0.0.0.0"
      - "--dev"
      - "--dev.period"
      - "1"
      - "--datadir"
      - "/geth_data"
      - "--syncmode"
      - "full"
      - "--rpc.allow-unprotected-txs"

  xagon-prover:
    container_name: xagon-prover
    image: hermeznetwork/zkevm-prover:v2.2.0 
    ports:
      # - 50051:50051 # Prover
      - 50052:50052 # Mock prover
      - 50061:50061 # MT
      - 50071:50071 # Executor
    volumes:
      - ./config/test.prover.config.json:/usr/src/app/config.json
    command: >
      zkProver -c /usr/src/app/config.json

  xagon-approve:
    container_name: xagon-approve
    image: xagon-node
    environment:
      - ZKEVM_NODE_STATEDB_HOST=xagon-state-db
    volumes:
      - ./config/sequencer.keystore:/pk/keystore
      - ./config/test.node.config.toml:/app/config.toml
      - ./config/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/xagon-node approve --network custom --custom-network-file /app/genesis.json --key-store-path /pk/keystore --pw testonly  --amount 1000000000000000000000000  --yes --cfg /app/config.toml"

  xagon-bridge-service:
    container_name: xagon-bridge-service
    image: xagon-bridge-service
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - ZKEVM_BRIDGE_DATABASE_USER=test_user
      - ZKEVM_BRIDGE_DATABASE_PASSWORD=test_password
      - ZKEVM_BRIDGE_DATABASE_NAME=test_db
      - ZKEVM_BRIDGE_DATABASE_HOST=xagon-bridge-db
      - ZKEVM_BRIDGE_DATABASE_PORT=5432
    volumes:
      - ./config/test.keystore.claimtx:/pk/keystore.claimtxmanager
      - ./config/config.bridge.toml:/app/config.toml
    command:
      - "/bin/sh"
      - "-c"
      - "/app/xagon-bridge run --cfg /app/config.toml"

  xagon-bridge-ui:
    container_name: xagon-bridge-ui
    image: xagon-bridge-ui
    ports:
      - 8090:80
    environment:
      - ETHEREUM_RPC_URL=http://52.40.99.48:8545
      - ETHEREUM_EXPLORER_URL=http://52.40.99.48:4000
      - ETHEREUM_BRIDGE_CONTRACT_ADDRESS=0xFc2f92CBFA1b38a4B38B412F582cf08028cBA9e0
      - ETHEREUM_FORCE_UPDATE_GLOBAL_EXIT_ROOT=true
      - ETHEREUM_PROOF_OF_EFFICIENCY_CONTRACT_ADDRESS=0x3fBC3dAAF173Ce3185757C5c38622536Ae76fe59
      - POLYGON_ZK_EVM_RPC_URL=http://52.40.99.48:8123
      - POLYGON_ZK_EVM_EXPLORER_URL=http://52.40.99.48:4001
      - POLYGON_ZK_EVM_BRIDGE_CONTRACT_ADDRESS=0xFc2f92CBFA1b38a4B38B412F582cf08028cBA9e0
      - POLYGON_ZK_EVM_NETWORK_ID=1
      - BRIDGE_API_URL=http://52.40.99.48:8080
      - ENABLE_FIAT_EXCHANGE_RATES=false
      - ENABLE_OUTDATED_NETWORK_MODAL=false
      - ENABLE_DEPOSIT_WARNING=true
      - ENABLE_REPORT_FORM=false
      - USE_FIAT_EXCHANGE_RATES=false
      - SHOW_OUTDATED_NETWORK_MODAL=false

  xagon-eth-tx-manager:
    container_name: xagon-eth-tx-manager
    image: xagon-node
    ports:
      - 9094:9091 # needed if metrics enabled
    environment:
      - ZKEVM_NODE_STATEDB_HOST=xagon-state-db
    volumes:
      - ./config/sequencer.keystore:/pk/sequencer.keystore
      - ./config/aggregator.keystore:/pk/aggregator.keystore
      - ./config/test.node.config.toml:/app/config.toml
      - ./config/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/xagon-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components eth-tx-manager"

  xagon-sequence-sender:
    container_name: xagon-sequence-sender
    image: xagon-node
    environment:
      - ZKEVM_NODE_STATEDB_HOST=xagon-state-db
      - ZKEVM_NODE_POOL_DB_HOST=xagon-pool-db
      - ZKEVM_NODE_SEQUENCER_SENDER_ADDRESS=0x28E803c70B44BA4ec2b27fa8b53DFd33d1b9c9b1
    volumes:
      - ./config/sequencer.keystore:/pk/sequencer.keystore
      - ./config/test.node.config.toml:/app/config.toml
      - ./config/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/xagon-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components sequence-sender"

  xagon-l2gaspricer:
    container_name: xagon-l2gaspricer
    image: xagon-node
    environment:
      - ZKEVM_NODE_POOL_DB_HOST=xagon-pool-db
    volumes:
      - ./config/sequencer.keystore:/pk/keystore
      - ./config/test.node.config.toml:/app/config.toml
      - ./config/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/xagon-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components l2gaspricer"

  xagon-bridge-db:
    container_name: xagon-bridge-db
    image: postgres
    expose:
      - 5436
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db
    command: [ "postgres", "-N", "500" ]

  xagon-data-availability:
    container_name: xagon-data-availability
    image: xagon-data-availability
    ports:
      - 8444:8444
    volumes:
      - ./config/test.da.toml:/app/config.toml
      - ./config/test-member.keystore:/pk/test-member.keystore
    command:
      - "/bin/sh"
      - "-c"
      - "/app/xagon-data-availability run --cfg /app/config.toml"

  xagon-data-availability-db:
    container_name: xagon-data-availability-db
    image: postgres
    ports:
      - 5437:5432
    environment:
      - POSTGRES_USER=committee_user
      - POSTGRES_PASSWORD=committee_password
      - POSTGRES_DB=committee_db
    command:
      - "postgres"
      - "-N"
      - "500"
