version: "3.5"
networks:
  default:
    name: xlayer
services:
  xlayer-sequencer-fork9:
    container_name: xlayer-sequencer
    image: okexchain/xlayer-node:origin_zjg_fork9_20240325075954_4ccc81eb
    ports:
      - 9092:9091 # needed if metrics enabled
      - 6060:6060
    environment:
      - ZKEVM_NODE_STATEDB_HOST=xlayer-state-db
      - ZKEVM_NODE_POOL_DB_HOST=xlayer-pool-db
    volumes:
      - ./config/fork9/test.node.config.toml:/app/config.toml
      - ./config/fork9/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/xlayer-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components sequencer"

  xlayer-json-rpc-fork9:
    container_name: xlayer-json-rpc
    image: okexchain/xlayer-node:origin_zjg_fork9_20240325075954_4ccc81eb
    ports:
      - 8123:8123
      - 8133:8133 # needed if WebSockets enabled
      - 9091:9091 # needed if metrics enabled
    environment:
      - ZKEVM_NODE_STATEDB_HOST=xlayer-state-db
      - ZKEVM_NODE_POOL_DB_HOST=xlayer-pool-db
    volumes:
      - ./config/fork9/test.node.config.toml:/app/config.toml
      - ./config/fork9/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/xlayer-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components rpc"

  xlayer-aggregator-fork9:
    container_name: xlayer-aggregator
    image: okexchain/xlayer-node:origin_zjg_fork9_20240325075954_4ccc81eb
    ports:
      - 50081:50081
      - 9093:9091 # needed if metrics enabled
    environment:
      - ZKEVM_NODE_STATEDB_HOST=xlayer-state-db
      - ZKEVM_NODE_AGGREGATOR_SENDER_ADDRESS=0xBAF25C3f0e7B21818Ed922a6e01bf25CA31dE19E
    volumes:
      - ./config/fork9/test.node.config.toml:/app/config.toml
      - ./config/fork9/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/xlayer-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components aggregator"

  xlayer-sync-fork9:
    container_name: xlayer-sync
    image: okexchain/xlayer-node:origin_zjg_fork9_20240325075954_4ccc81eb
    ports:
      - 9095:9091 # needed if metrics enabled
    environment:
      - ZKEVM_NODE_STATEDB_HOST=xlayer-state-db
    volumes:
      - ./config/fork9/test.node.config.toml:/app/config.toml
      - ./config/fork9/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/xlayer-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components synchronizer"

  xlayer-executor-fork9:
    container_name: xlayer-executor
    image: okexchain/xlayer-prover:origin_zjg_fork9_20240325080109_458b8d26
    ports:
      - 50061:50061 # MT
      - 50071:50071 # Executor
    volumes:
      - ./config/fork9/test.executor.config.json:/usr/src/app/config.json
    command: >
      zkProver -c /usr/src/app/config.json

  xlayer-prover-fork9:
    container_name: xlayer-prover
    image: okexchain/xlayer-prover:origin_zjg_fork9_20240325080109_458b8d26
    volumes:
      - /data/zkevm/v6.0.0-rc.1-fork.9/config:/app/config
      - ./config/fork9/test.prover.config.json:/usr/src/app/config.json
    command: >
      zkProver -c /usr/src/app/config.json

  xlayer-bridge-service-fork9:
    container_name: xlayer-bridge-service
    image: okexchain/xlayer-bridge-service:origin_zjg_fork9_20240325080026_53a8055
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      - ZKEVM_BRIDGE_DATABASE_USER=test_user
      - ZKEVM_BRIDGE_DATABASE_PASSWORD=test_password
      - ZKEVM_BRIDGE_DATABASE_NAME=test_db
      - ZKEVM_BRIDGE_DATABASE_HOST=xlayer-bridge-db
      - ZKEVM_BRIDGE_DATABASE_PORT=5432
    volumes:
      - ./config/test.keystore.claimtx:/pk/keystore.claimtxmanager
      - ./config/fork9/config.bridge.toml:/app/config.toml
      - ./config/root-ca-cert:/app/root-ca-cert
    command:
      - "/bin/sh"
      - "-c"
      - "/app/xlayer-bridge run --cfg /app/config.toml"

  xlayer-eth-tx-manager-fork9:
    container_name: xlayer-eth-tx-manager
    image: okexchain/xlayer-node:origin_zjg_fork9_20240325075954_4ccc81eb
    ports:
      - 9094:9091 # needed if metrics enabled
    environment:
      - ZKEVM_NODE_STATEDB_HOST=xlayer-state-db
    volumes:
      - ./config/sequencer.keystore:/pk/sequencer.keystore
      - ./config/aggregator.keystore:/pk/aggregator.keystore
      - ./config/fork9/test.node.config.toml:/app/config.toml
      - ./config/fork9/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/xlayer-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components eth-tx-manager"

  xlayer-sequence-sender-fork9:
    container_name: xlayer-sequence-sender
    image: okexchain/xlayer-node:origin_zjg_fork9_20240325075954_4ccc81eb
    environment:
      - ZKEVM_NODE_STATEDB_HOST=xlayer-state-db
      - ZKEVM_NODE_POOL_DB_HOST=xlayer-pool-db
      - ZKEVM_NODE_SEQUENCER_SENDER_ADDRESS=0x28E803c70B44BA4ec2b27fa8b53DFd33d1b9c9b1
    volumes:
      - ./config/sequencer.keystore:/pk/sequencer.keystore
      - ./config/fork9/test.node.config.toml:/app/config.toml
      - ./config/fork9/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/xlayer-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components sequence-sender"

  xlayer-l2gaspricer-fork9:
    container_name: xlayer-l2gaspricer
    image: okexchain/xlayer-node:origin_zjg_fork9_20240325075954_4ccc81eb
    environment:
      - ZKEVM_NODE_POOL_DB_HOST=xlayer-pool-db
    volumes:
      - ./config/sequencer.keystore:/pk/keystore
      - ./config/fork9/test.node.config.toml:/app/config.toml
      - ./config/fork9/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/xlayer-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components l2gaspricer"

  xlayer-data-availability-fork9:
    container_name: xlayer-data-availability
    image: okexchain/xlayer-data-availability:origin_zjg_fork9_20240325085836_f84bdab
    ports:
      - 8444:8444
    volumes:
      - ./config/fork9/test.da.toml:/app/config.toml
      - ./config/test-member.keystore:/pk/test-member.keystore
    command:
      - "/bin/sh"
      - "-c"
      - "/app/xlayer-data-availability run --cfg /app/config.toml"

  xlayer-bridge-db:
    container_name: xlayer-bridge-db
    image: postgres
    expose:
      - 5436
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_db
    command: [ "postgres", "-N", "500" ]

  xlayer-bridge-redis:
    container_name: xlayer-bridge-redis
    image: redis
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    expose:
      - 6379
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=my_password
      - REDIS_PORT=6379
      - REDIS_DATABASES=8

  xlayer-data-availability-db:
    container_name: xlayer-data-availability-db
    image: postgres
    ports:
      - 5437:5432
    environment:
      - POSTGRES_USER=committee_user
      - POSTGRES_PASSWORD=committee_password
      - POSTGRES_DB=committee_db
    command:
      - "postgres"
      - "-N"
      - "500"

  xlayer-state-db:
    container_name: xlayer-state-db
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./config/sql/init_prover_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=state_user
      - POSTGRES_PASSWORD=state_password
      - POSTGRES_DB=state_db
    command:
      - "postgres"
      - "-N"
      - "500"

  xlayer-pool-db:
    container_name: xlayer-pool-db
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=pool_user
      - POSTGRES_PASSWORD=pool_password
      - POSTGRES_DB=pool_db
    command:
      - "postgres"
      - "-N"
      - "500"

  xlayer-event-db:
    container_name: xlayer-event-db
    image: postgres
    ports:
      - 5435:5432
    volumes:
      - ./config/sql/init_event_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=event_user
      - POSTGRES_PASSWORD=event_password
      - POSTGRES_DB=event_db
    command:
      - "postgres"
      - "-N"
      - "500"

  xlayer-bridge-ui-fork9:
    container_name: xlayer-bridge-ui
    image: hermeznetwork/zkevm-bridge-ui:etrog-v2
    ports:
      - 8090:80
    environment:
      - ETHEREUM_RPC_URL=https://rpc.ankr.com/eth_sepolia/578c95407e7831f0ac1ef79cacae294dc9bf8307121ca9fffaf1e556a5cca662
      - ETHEREUM_EXPLORER_URL=http://16.162.168.223:4000
      - ETHEREUM_ROLLUP_MANAGER_ADDRESS={ETHEREUM_ROLLUP_MANAGER_ADDRESS}
      - ETHEREUM_BRIDGE_CONTRACT_ADDRESS={ETHEREUM_BRIDGE_CONTRACT_ADDRESS}
      - ETHEREUM_FORCE_UPDATE_GLOBAL_EXIT_ROOT=true
      - ETHEREUM_PROOF_OF_EFFICIENCY_CONTRACT_ADDRESS={ETHEREUM_PROOF_OF_EFFICIENCY_CONTRACT_ADDRESS}
      - POLYGON_ZK_EVM_RPC_URL=http://16.162.168.223:8123
      - POLYGON_ZK_EVM_EXPLORER_URL=http://16.162.168.223:4001
      - POLYGON_ZK_EVM_BRIDGE_CONTRACT_ADDRESS={POLYGON_ZK_EVM_BRIDGE_CONTRACT_ADDRESS}
      - POLYGON_ZK_EVM_NETWORK_ID=1
      - BRIDGE_API_URL=http://16.162.168.223:8080
      - ENABLE_FIAT_EXCHANGE_RATES=false
      - ENABLE_OUTDATED_NETWORK_MODAL=false
      - ENABLE_DEPOSIT_WARNING=true
      - ENABLE_REPORT_FORM=false
      - USE_FIAT_EXCHANGE_RATES=false
      - SHOW_OUTDATED_NETWORK_MODAL=false


  xlayer-bridge-coin-kafka:
    image: wurstmeister/kafka
    container_name: xlayer-bridge-coin-kafka
    expose:
      - 9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://localhost:9123
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9123
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: kafka-zookeeper:2181
      KAFKA_CREATE_TOPICS: "explorer_chainAddressPrice_push:1:1"

  kafka-zookeeper:
    image: wurstmeister/zookeeper
    container_name: kafka-zookeeper
    ports:
      - "2181:2181"
    expose:
      - 2181
