version: "3.5"
networks:
  default:
    name: xlayer
services:
  xlayer-stateless-executor:
    container_name: xlayer-stateless-executor
    image: hermeznetwork/zkevm-prover:v6.0.2-RC3
    ports:
      - 0.0.0.0:50061:50061 # MT
      - 0.0.0.0:50071:50071 # Executor
    volumes:
      - ./config/fork9/test.stateless_executor.config.json:/usr/src/app/config.json
    command: >
      zkProver -c /usr/src/app/config.json
    depends_on:
      xlayer-state-db:
        condition: service_healthy

  xlayer-state-db:
    container_name: xlayer-state-db
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./config/sql/init_prover_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=state_user
      - POSTGRES_PASSWORD=state_password
      - POSTGRES_DB=state_db
    command:
      - "postgres"
      - "-N"
      - "500"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U state_user -d state_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
      
  xlayer-seqsender:
    container_name: xlayer-seqsender
    image: hermeznetwork/zkevm-seqsender:v0.1.1-RC1
    volumes:
      - ./config/sequencer.keystore:/pk/sequencer.keystore
      - ./config/fork9/seqsender.node.config.toml:/app/config.toml
      - ./config/fork9/test.genesis.config.json:/app/genesis.json
    restart: always
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-seqsender run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components sequence-sender"

  xlayer-aggregator:
    container_name: xlayer-aggregator
    image: hermeznetwork/zkevm-aggregator:v0.0.1-RC7
    ports:
      - 50081:50081
    volumes:
      - ./config/aggregator.keystore:/pk/aggregator.keystore
      - ./config/fork9/aggregator.node.config.toml:/app/config.toml
      - ./config/fork9/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-aggregator run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml"

  xlayer-aggregator-db:
    container_name: xlayer-aggregator-db
    image: postgres:15
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=aggregator_user
      - POSTGRES_PASSWORD=aggregator_password
      - POSTGRES_DB=aggregator_db
    command:
      - "postgres"
      - "-N"
      - "500"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aggregator_user -d aggregator_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  xlayer-prover:
    container_name: xlayer-prover
    image: hermeznetwork/zkevm-prover:v6.0.1
    volumes:
      - ./config/fork9/test.prover.config.json:/usr/src/app/config.json
    command: >
      zkProver -c /usr/src/app/config.json
    depends_on:
      xlayer-state-db:
        condition: service_healthy