version: "3.5"
networks:
  default:
    name: zkevm
services:
  zkevm-sequencer-fork6:
    container_name: zkevm-sequencer
    image: zkevm-node-fork6
    ports:
      - 9092:9091 # needed if metrics enabled
      - 6060:6060
    environment:
      - ZKEVM_NODE_STATEDB_HOST=zkevm-state-db
      - ZKEVM_NODE_POOL_DB_HOST=zkevm-pool-db
    volumes:
      - ./config/fork6/test.node.config.toml:/app/config.toml
      - ./config/fork6/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components sequencer"

  zkevm-json-rpc-fork6:
    container_name: zkevm-json-rpc
    image: zkevm-node-fork6
    ports:
      - 8123:8123
      - 8133:8133 # needed if WebSockets enabled
      - 9091:9091 # needed if metrics enabled
    environment:
      - ZKEVM_NODE_STATEDB_HOST=zkevm-state-db
      - ZKEVM_NODE_POOL_DB_HOST=zkevm-pool-db
    volumes:
      - ./config/fork6/test.node.config.toml:/app/config.toml
      - ./config/fork6/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components rpc"

  zkevm-aggregator-fork6:
    container_name: zkevm-aggregator
    image: zkevm-node-fork6
    ports:
      - 50081:50081
      - 9093:9091 # needed if metrics enabled
    environment:
      - ZKEVM_NODE_STATEDB_HOST=zkevm-state-db
    volumes:
      - ./config/fork6/test.node.config.toml:/app/config.toml
      - ./config/fork6/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components aggregator"

  zkevm-sync-fork6:
    container_name: zkevm-sync
    image: zkevm-node-fork6
    ports:
      - 9095:9091 # needed if metrics enabled
    environment:
      - ZKEVM_NODE_STATEDB_HOST=zkevm-state-db
    volumes:
      - ./config/fork6/test.node.config.toml:/app/config.toml
      - ./config/fork6/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components synchronizer"

  zkevm-executor-fork6:
    container_name: zkevm-executor
    image: hermeznetwork/zkevm-prover:v3.0.2 
    ports:
      - 50061:50061 # MT
      - 50071:50071 # Executor
    volumes:
      - ./config/fork6/test.executor.config.json:/usr/src/app/config.json
    command: >
      zkProver -c /usr/src/app/config.json

  zkevm-prover-fork6:
    container_name: zkevm-prover
    image: hermeznetwork/zkevm-prover:v3.0.2 
    volumes:
      - /data/zkevm/v3.0.0-RC3-fork.6/config:/app/config
      - ./config/fork6/test.prover.config.json:/usr/src/app/config.json
    command: >
      zkProver -c /usr/src/app/config.json

  zkevm-eth-tx-manager-fork6:
    container_name: zkevm-eth-tx-manager
    image: zkevm-node-fork6
    ports:
      - 9094:9091 # needed if metrics enabled
    environment:
      - ZKEVM_NODE_STATEDB_HOST=zkevm-state-db
    volumes:
      - ./config/sequencer.keystore:/pk/sequencer.keystore
      - ./config/aggregator.keystore:/pk/aggregator.keystore
      - ./config/fork6/test.node.config.toml:/app/config.toml
      - ./config/fork6/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components eth-tx-manager"

  zkevm-sequence-sender-fork6:
    container_name: zkevm-sequence-sender
    image: zkevm-node-fork6
    environment:
      - ZKEVM_NODE_STATEDB_HOST=zkevm-state-db
      - ZKEVM_NODE_POOL_DB_HOST=zkevm-pool-db
    volumes:
      - ./config/sequencer.keystore:/pk/sequencer.keystore
      - ./config/fork6/test.node.config.toml:/app/config.toml
      - ./config/fork6/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components sequence-sender"

  zkevm-l2gaspricer-fork6:
    container_name: zkevm-l2gaspricer
    image: zkevm-node-fork6
    environment:
      - ZKEVM_NODE_POOL_DB_HOST=zkevm-pool-db
    volumes:
      - ./config/sequencer.keystore:/pk/keystore
      - ./config/fork6/test.node.config.toml:/app/config.toml
      - ./config/fork6/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components l2gaspricer"

  zkevm-sequencer-fork7:
    container_name: zkevm-sequencer
    image: zkevm-node-fork7
    ports:
      - 9092:9091 # needed if metrics enabled
      - 6060:6060
    environment:
      - ZKEVM_NODE_STATEDB_HOST=zkevm-state-db
      - ZKEVM_NODE_POOL_DB_HOST=zkevm-pool-db
    volumes:
      - ./config/fork7/test.node.config.toml:/app/config.toml
      - ./config/fork7/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components sequencer"

  zkevm-json-rpc-fork7:
    container_name: zkevm-json-rpc
    image: zkevm-node-fork7
    ports:
      - 8123:8123
      - 8133:8133 # needed if WebSockets enabled
      - 9091:9091 # needed if metrics enabled
    environment:
      - ZKEVM_NODE_STATEDB_HOST=zkevm-state-db
      - ZKEVM_NODE_POOL_DB_HOST=zkevm-pool-db
    volumes:
      - ./config/fork7/test.node.config.toml:/app/config.toml
      - ./config/fork7/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components rpc"

  zkevm-aggregator-fork7:
    container_name: zkevm-aggregator
    image: zkevm-node-fork7
    ports:
      - 50081:50081
      - 9093:9091 # needed if metrics enabled
    environment:
      - ZKEVM_NODE_STATEDB_HOST=zkevm-state-db
    volumes:
      - ./config/fork7/test.node.config.toml:/app/config.toml
      - ./config/fork7/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components aggregator"

  zkevm-sync-fork7:
    container_name: zkevm-sync
    image: zkevm-node-fork7
    ports:
      - 9095:9091 # needed if metrics enabled
    environment:
      - ZKEVM_NODE_STATEDB_HOST=zkevm-state-db
    volumes:
      - ./config/fork7/test.node.config.toml:/app/config.toml
      - ./config/fork7/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components synchronizer"

  zkevm-executor-fork7:
    container_name: zkevm-executor
    image: hermeznetwork/zkevm-prover:v4.0.14
    ports:
      - 50061:50061 # MT
      - 50071:50071 # Executor
    volumes:
      - ./config/fork7/test.executor.config.json:/usr/src/app/config.json
    command: >
      zkProver -c /usr/src/app/config.json

  zkevm-prover-fork7:
    container_name: zkevm-prover
    image: hermeznetwork/zkevm-prover:v4.0.14
    volumes:
      - /data/zkevm/v4.0.0-rc.6-fork.7/config:/app/config
      - ./config/fork7/test.prover.config.json:/usr/src/app/config.json
    command: >
      zkProver -c /usr/src/app/config.json

  zkevm-eth-tx-manager-fork7:
    container_name: zkevm-eth-tx-manager
    image: zkevm-node-fork7
    ports:
      - 9094:9091 # needed if metrics enabled
    environment:
      - ZKEVM_NODE_STATEDB_HOST=zkevm-state-db
    volumes:
      - ./config/sequencer.keystore:/pk/sequencer.keystore
      - ./config/aggregator.keystore:/pk/aggregator.keystore
      - ./config/fork7/test.node.config.toml:/app/config.toml
      - ./config/fork7/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components eth-tx-manager"

  zkevm-sequence-sender-fork7:
    container_name: zkevm-sequence-sender
    image: zkevm-node-fork7
    environment:
      - ZKEVM_NODE_STATEDB_HOST=zkevm-state-db
      - ZKEVM_NODE_POOL_DB_HOST=zkevm-pool-db
    volumes:
      - ./config/sequencer.keystore:/pk/sequencer.keystore
      - ./config/fork7/test.node.config.toml:/app/config.toml
      - ./config/fork7/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components sequence-sender"

  zkevm-l2gaspricer-fork7:
    container_name: zkevm-l2gaspricer
    image: zkevm-node-fork7
    environment:
      - ZKEVM_NODE_POOL_DB_HOST=zkevm-pool-db
    volumes:
      - ./config/sequencer.keystore:/pk/keystore
      - ./config/fork7/test.node.config.toml:/app/config.toml
      - ./config/fork7/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components l2gaspricer"

  zkevm-state-db:
    container_name: zkevm-state-db
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./config/sql/init_prover_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=state_user
      - POSTGRES_PASSWORD=state_password
      - POSTGRES_DB=state_db
    command:
      - "postgres"
      - "-N"
      - "500"

  zkevm-pool-db:
    container_name: zkevm-pool-db
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=pool_user
      - POSTGRES_PASSWORD=pool_password
      - POSTGRES_DB=pool_db
    command:
      - "postgres"
      - "-N"
      - "500"

  zkevm-event-db:
    container_name: zkevm-event-db
    image: postgres
    ports:
      - 5435:5432
    volumes:
      - ./config/sql/init_event_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=event_user
      - POSTGRES_PASSWORD=event_password
      - POSTGRES_DB=event_db
    command:
      - "postgres"
      - "-N"
      - "500"

