version: "3.5"
networks:
  default:
    name: xlayer
services:
  xlayer-executor:
    container_name: xlayer-executor
    image: hermeznetwork/zkevm-prover:v9.0.0-RC1-fork.13
    ports:
      - 0.0.0.0:50061:50061 # MT
      - 0.0.0.0:50071:50071 # Executor
    volumes:
      - ./config/erigon/test.stateless_executor.config.json:/usr/src/app/config.json
    command: >
      zkProver -c /usr/src/app/config.json
    depends_on:
      xlayer-state-db:
        condition: service_healthy

  xlayer-state-db:
    container_name: xlayer-state-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=state_user
      - POSTGRES_PASSWORD=state_password
      - POSTGRES_DB=state_db
    command:
      - "postgres"
      - "-N"
      - "500"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U state_user -d state_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
      
  xlayer-seqs:
    container_name: xlayer-seqs
    image: cdk
    volumes:
      - ./data/cdk:/tmp/cdk
      - ./config/sequencer.keystore:/pk/sequencer.keystore
      - ./config/erigon/cdk.config.toml:/app/config.toml
      - ./config/erigon/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/usr/local/bin/cdk-node run --cfg /app/config.toml --custom-network-file /app/genesis.json --components sequence-sender"

  xlayer-agg:
    container_name: xlayer-agg
    image: cdk
    ports:
      - 50081:50081
    volumes:
      - ./config/aggregator.keystore:/pk/aggregator.keystore
      - ./config/erigon/cdk.config.toml:/app/config.toml
      - ./config/erigon/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/usr/local/bin/cdk-node run --cfg /app/config.toml --network custom --custom-network-file /app/genesis.json  --components aggregator"

  xlayer-agg-db:
    container_name: xlayer-agg-db
    image: postgres:15
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=aggregator_user
      - POSTGRES_PASSWORD=aggregator_password
      - POSTGRES_DB=aggregator_db
    command:
      - "postgres"
      - "-N"
      - "500"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aggregator_user -d aggregator_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  xlayer-prover:
    container_name: xlayer-prover
    image: hermeznetwork/zkevm-prover:v9.0.0-RC1-fork.13
    volumes:
      - ./config/erigon/test.prover.config.json:/usr/src/app/config.json
    command: >
      zkProver -c /usr/src/app/config.json
    depends_on:
      xlayer-state-db:
        condition: service_healthy

  xlayer-approve:
    container_name: xlayer-approve
    image: hermeznetwork/zkevm-node:v0.6.6
    volumes:
      - ./config/sequencer.keystore:/pk/keystore
      - ./config/erigon/test.node.config.toml:/app/config.toml
      - ./config/erigon/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node approve --network custom --custom-network-file /app/genesis.json --key-store-path /pk/keystore --pw password --am 115792089237316195423570985008687907853269984665640564039457584007913129639935 -y --cfg /app/config.toml"

  xlayer-seq:
    container_name: xlayer-seq
    image: cdk-erigon
    environment:
      - CDK_ERIGON_SEQUENCER=1
    ports:
      - 8123:8545
      - 6900:6900
    volumes:
      - ./config/erigon/test.erigon.seq.config.yaml:/usr/src/app/config.yaml
      - ./data/seq:/home/erigon/.local/share/erigon
      - ./config/erigon/dynamic-mynetwork-allocs.json:/usr/src/app/dynamic-mynetwork-allocs.json
      - ./config/erigon/dynamic-mynetwork-chainspec.json:/usr/src/app/dynamic-mynetwork-chainspec.json
      - ./config/erigon/dynamic-mynetwork-conf.json:/usr/src/app/dynamic-mynetwork-conf.json
    command: >
      cdk-erigon --http.vhosts=* --http.corsdomain=* --ws --config=/usr/src/app/config.yaml

  xlayer-da:
    container_name: xlayer-da
    image: okexchain/xlayer-data-availability:origin_release_v0.3.1_20240411102017_f84bdab
    ports:
      - 8444:8444
    volumes:
      - ./config/erigon/test.da.toml:/app/config.toml
      - ./config/test-member.keystore:/pk/test-member.keystore
    command:
      - "/bin/sh"
      - "-c"
      - "/app/xlayer-data-availability run --cfg /app/config.toml"

  xlayer-da-db:
    container_name: xlayer-da-db
    image: postgres
    ports:
      - 5437:5432
    environment:
      - POSTGRES_USER=committee_user
      - POSTGRES_PASSWORD=committee_password
      - POSTGRES_DB=committee_db
    command:
      - "postgres"
      - "-N"
      - "500"

  # xlayer-permissionless-db:
  #   container_name: xlayer-permissionless-db
  #   image: postgres:15
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 2G
  #       reservations:
  #         memory: 1G
  #   ports:
  #     - 5444:5432
  #   volumes:
  #     - ./config/sql/single_db_server.sql:/docker-entrypoint-initdb.d/init.sql
  #   environment:
  #     - POSTGRES_USER=test_user
  #     - POSTGRES_PASSWORD=test_password
  #     - POSTGRES_DB=test_db
  #   command:
  #     - "postgres"
  #     - "-N"
  #     - "500"