version: "3.5"
networks:
  default:
    name: xlayer
services:
  xlayer-stateless-executor:
    container_name: xlayer-stateless-executor
    image: hermeznetwork/zkevm-prover:v6.0.2-RC3
    ports:
      - 0.0.0.0:50061:50061 # MT
      - 0.0.0.0:50071:50071 # Executor
    volumes:
      - ./config/fork9/test.stateless_executor.config.json:/usr/src/app/config.json
    command: >
      zkProver -c /usr/src/app/config.json
      