[Log]
Level = "info"
Outputs = ["stdout"]

[SyncDB]
Database = "postgres"
User = "test_user"
Password = "test_password"
Name = "test_db"
Host = "x1-bridge-db"
Port = "5432"
MaxConns = 20
TableSuffix = ""

[ClaimTxManager]
Enabled = true
FreeGas = true
FrequencyToMonitorTxs = "1s"
PrivateKey = {Path = "/pk/keystore.claimtxmanager", Password = "testonly"}
RetryInterval = "1s"
RetryNumber = 10
AuthorizedClaimMessageAddresses = []

[Etherman]
L1URL = "https://rpc.ankr.com/eth_sepolia/578c95407e7831f0ac1ef79cacae294dc9bf8307121ca9fffaf1e556a5cca662"
L2URLs = ["http://x1-json-rpc:8123"]
L1ChainId = 11155111 
L2ChainIds = [195]

[Synchronizer]
SyncInterval = "1s"
SyncChunkSize = 100

[BridgeController]
Store = "postgres"
Height = 32

[BridgeServer]
GRPCPort = "9090"
HTTPPort = "8080"
CacheSize = 100000
DefaultPageLimit = 25
MaxPageLimit = 100
BridgeVersion = "v1"
SentinelConfigFilePath = "/app/sentinel_config.json"
    [BridgeServer.DB]
    Database = "postgres"
    User = "test_user"
    Password = "test_password"
    Name = "test_db"
    Host = "x1-bridge-db"
    Port = "5432"
    MaxConns = 20
    TableSuffix = ""
    [BridgeServer.Redis]
    Addrs = ["x1-bridge-redis:6379"]
    Username = ""
    Password = ""
    DB = 0
    MockPrice = true

[CoinKafkaConsumer]
Brokers = ["x1-bridge-coin-kafka:9092"]
Topics = ["explorer_chainAddressPrice_push"]
ConsumerGroupID = "x1-bridge-service"
InitialOffset = -1
Username = ""
Password = ""
RootCAPath = "/app/root-ca-cert"

[NetworkConfig]
GenBlockNumber = 5371065 
PolygonBridgeAddress = "0xCFF273F4344688Ad345a6EFb28De168Ce169C3E1"
PolygonZkEVMGlobalExitRootAddress = "0x9923c9ce918134202E0831668E7C32966dfa9d48"
PolygonRollupManagerAddress = "0xe14fc607c46344850A66F09175E851D0e7eB9684"
PolygonZkEvmAddress = "0x39Ddea7761cDA4FB17c8f39C85C0a5de934D3880"
L2PolygonBridgeAddresses = ["0xCFF273F4344688Ad345a6EFb28De168Ce169C3E1"]
