
[Aggregator]
Host = "0.0.0.0"
Port = 50081
RetryTime = "5s"
VerifyProofInterval = "10s"
TxProfitabilityCheckerType = "acceptall"
TxProfitabilityMinReward = "1.1"
ProofStatePollingInterval = "5s"
SenderAddress = "0x694D3f1487e17A96edA98Ced6ae3eC751a08E9Fe"
CleanupLockedProofsInterval = "2m"
GeneratingProofCleanupThreshold = "10m"
ForkId = 9
WitnessURL = "http://erigon-seq:8545"
LERContract = "0xa40D5f56745a118D0906a34E69aeC8C0Db1cB8fA"
	[Aggregator.DB]
		Name = "aggregator_db"
		User = "aggregator_user"
		Password = "aggregator_password"
		Host = "erigon-aggregator-db"
		Port = "5432"
		EnableLog = false	
		MaxConns = 200
	[Aggregator.Log]
		Environment = "development" # "production" or "development"
		Level = "info"
		Outputs = ["stderr"]
	[Aggregator.StreamClient]
		Server = "erigon-seq:6900"
	[Aggregator.EthTxManager]
		FrequencyToMonitorTxs = "1s"
		WaitTxToBeMined = "2m"
		ConsolidationL1ConfirmationBlocks = 5
		FinalizationL1ConfirmationBlocks = 10
		WaitReceiptToBeGenerated = "8s"
		PrivateKeys = [
			{Path = "/pk/aggregator.keystore", Password = "password"},
		]
		ForcedGas = 0
		GasPriceMarginFactor = 1
		MaxGasPriceLimit = 0
		PersistenceFilename = "/ethtxmanager_aggregator.json"
			[Aggregator.EthTxManager.Etherman]
				URL = "https://rpc.eu-central-1.gateway.fm/v4/ethereum/non-archival/sepolia?apikey=IkrTRMPAlsjfgTyKz1Xfa5ldS8XSc0PN.En5aU2Gwdxvf3zk2"
				L1ChainID = 11155111
				HTTPHeaders = []
	[Aggregator.Synchronizer]
		[Aggregator.Synchronizer.DB]
			Name = "state_db"
			User = "state_user"
			Password = "state_password"
			Host = "erigon-state-db"
			Port = "5432"
			EnableLog = false
			MaxConns = 10
		[Aggregator.Synchronizer.Synchronizer]
			SyncInterval = "10s"
			SyncChunkSize = 1000
			GenesisBlockNumber = {genesisBlockNumber}
		[Aggregator.Synchronizer.Log]
			Environment = "development" # "production" or "development"
			Level = "debug"
			Outputs = ["stderr"]

[EventLog]
	[EventLog.DB]