ForkUpgradeBatchNumber = 0
ForkUpgradeNewForkId = 0

[Log]
Environment = "development" # "production" or "development"
Level = "info"
Outputs = ["stderr"]

[Etherman]
	URL="https://rpc.ankr.com/eth_sepolia/578c95407e7831f0ac1ef79cacae294dc9bf8307121ca9fffaf1e556a5cca662"
	ForkIDChunkSize=100
	[Etherman.EthermanConfig]
		URL="https://rpc.ankr.com/eth_sepolia/578c95407e7831f0ac1ef79cacae294dc9bf8307121ca9fffaf1e556a5cca662"
		MultiGasProvider=false
		L1ChainID=11155111
		HTTPHeaders=[]
		[Etherman.EthermanConfig.Etherscan]
			ApiKey=""
			Url="https://api.etherscan.io/api?module=gastracker&action=gasoracle&apikey="

[Common]
NetworkID = 1
IsValidiumMode = true
ContractVersions = "banana"

[SequenceSender]
WaitPeriodSendSequence = "15s"
LastBatchVirtualizationTimeMaxWaitPeriod = "10s"
L1BlockTimestampMargin = "30s"
MaxTxSizeForL1 = 131072
L2Coinbase = "0x4820E45eB6Cf99074389544F83FE1F30084bdAb7"
PrivateKey = {Path = "/pk/sequencer.keystore", Password = "password"}
SequencesTxFileName = "sequencesender.json"
GasOffset = 80000
WaitPeriodPurgeTxFile = "60m"
MaxPendingTx = 1
MaxBatchesForL1 = 300
BlockFinality = "FinalizedBlock"
RPCURL = "http://xlayer-seq:8545"
GetBatchWaitInterval = "10s"
	[SequenceSender.EthTxManager]
		FrequencyToMonitorTxs = "1s"
		WaitTxToBeMined = "2m"
		GetReceiptMaxTime = "250ms"
		GetReceiptWaitInterval = "1s"
		PrivateKeys = [
			{Path = "/pk/sequencer.keystore", Password = "password"},
		]
		ForcedGas = 0
		GasPriceMarginFactor = 1
		MaxGasPriceLimit = 0
		StoragePath = "ethtxmanager.sqlite"
		ReadPendingL1Txs = false
		SafeStatusL1NumberOfBlocks = 0
		FinalizedStatusL1NumberOfBlocks = 0
			[SequenceSender.EthTxManager.Etherman]
				URL = "https://rpc.ankr.com/eth_sepolia/578c95407e7831f0ac1ef79cacae294dc9bf8307121ca9fffaf1e556a5cca662"
				MultiGasProvider = false
				L1ChainID = 11155111
[Aggregator]
# GRPC server host
Host = "0.0.0.0"
# GRPC server port
Port = 50081
RetryTime = "5s"
VerifyProofInterval = "10s"
ProofStatePollingInterval = "5s"
TxProfitabilityCheckerType = "acceptall"
TxProfitabilityMinReward = "1.1"
IntervalAfterWhichBatchConsolidateAnyway="0s"
BatchProofSanityCheckEnabled = true
#  ChainID is L2ChainID. Is populated on runtimme
ChainID = 0
ForkId = 13
SenderAddress = "0x694D3f1487e17A96edA98Ced6ae3eC751a08E9Fe"
CleanupLockedProofsInterval = "2m"
GeneratingProofCleanupThreshold = "10m"
GasOffset = 0
RPCURL = "http://xlayer-seq:8545"
WitnessURL = "http://xlayer-seq:8545"
UseFullWitness = false
SettlementBackend = "l1"
AggLayerTxTimeout = "5m"
AggLayerURL = ""
SyncModeOnlyEnabled = false
	[Aggregator.SequencerPrivateKey]
		Path = "/pk/sequencer.keystore"
		Password = "password"
	[Aggregator.DB]
		Name = "aggregator_db"
		User = "aggregator_user"
		Password = "aggregator_password"
		Host = "xlayer-agg-db"
		Port = "5432"
		EnableLog = false	
		MaxConns = 200
	[Aggregator.Log]
		Environment = "development" # "production" or "development"
		Level = "info"
		Outputs = ["stderr"]
	[Aggregator.EthTxManager]
		FrequencyToMonitorTxs = "1s"
		WaitTxToBeMined = "2m"
		GetReceiptMaxTime = "250ms"
		GetReceiptWaitInterval = "1s"
		PrivateKeys = [
			{Path = "/pk/aggregator.keystore", Password = "password"},
		]
		ForcedGas = 0
		GasPriceMarginFactor = 1
		MaxGasPriceLimit = 0
		StoragePath = ""
		ReadPendingL1Txs = false
		SafeStatusL1NumberOfBlocks = 0
		FinalizedStatusL1NumberOfBlocks = 0
			[Aggregator.EthTxManager.Etherman]
				URL = "https://rpc.ankr.com/eth_sepolia/578c95407e7831f0ac1ef79cacae294dc9bf8307121ca9fffaf1e556a5cca662"
				L1ChainID = 11155111
				HTTPHeaders = []
	[Aggregator.Synchronizer]
		[Aggregator.Synchronizer.Log]
			Environment = "development" # "production" or "development"
			Level = "info"
			Outputs = ["stderr"]
		[Aggregator.Synchronizer.SQLDB]
			DriverName = "sqlite3"
			DataSource = "file:/tmp/cdk/aggregator_sync_db.sqlite"
		[Aggregator.Synchronizer.Synchronizer]
			SyncInterval = "10s"
			SyncChunkSize = 1000
			GenesisBlockNumber = {genesisBlockNumber}
			SyncUpToBlock = "finalized"
			BlockFinality = "finalized"
			OverrideStorageCheck = false
		[Aggregator.Synchronizer.Etherman]
			L1URL = "https://rpc.ankr.com/eth_sepolia/578c95407e7831f0ac1ef79cacae294dc9bf8307121ca9fffaf1e556a5cca662"
			ForkIDChunkSize = 100
			L1ChainID = 11155111
			PararellBlockRequest = false
			[Aggregator.Synchronizer.Etherman.Contracts]
				GlobalExitRootManagerAddr = "{polygonZkEVMGlobalExitRootAddress}"
				RollupManagerAddr = "{polygonRollupManagerAddress}"
				ZkEVMAddr = "{polygonZkEVMAddress}"
			[Aggregator.Synchronizer.Etherman.Validium]
				Enabled = true
				# L2URL, empty ask to contract
				TrustedSequencerURL = ""
				RetryOnDACErrorInterval = "1m"
				DataSourcePriority = ["trusted", "external"]
			[Aggregator.Synchronizer.Etherman.Validium.Translator]
				FullMatchRules = []
			[Aggregator.Synchronizer.Etherman.Validium.RateLimit]
				NumRequests = 1000
				Interval = "1s"
[ReorgDetectorL1]
DBPath = "/tmp/cdk/reorgdetectorl1"

[ReorgDetectorL2]
DBPath = "/tmp/cdk/reorgdetectorl2"

[L1InfoTreeSync]
DBPath = "/tmp/cdk/L1InfoTreeSync.sqlite"
GlobalExitRootAddr="0xcdBDBd809e75123f36c6Eb90845050a02d5C91D9"
RollupManagerAddr = "0x3ff239788ea041B2FeAEa01F0Fc160103907c1Ef"
SyncBlockChunkSize=10
BlockFinality="LatestBlock"
URLRPCL1="http://xlayer-seq:8545"
WaitForNewBlocksPeriod="100ms"
InitialBlock= {genesisBlockNumber}

[AggOracle]
TargetChainType="EVM"
URLRPCL1=""
BlockFinality="FinalizedBlock"
WaitPeriodNextGER="100ms"
	[AggOracle.EVMSender]
		GlobalExitRootL2="{polygonZkEVMGlobalExitRootAddress}"
		URLRPCL2=""
		ChainIDL2=1337
		GasOffset=0
		WaitPeriodMonitorTx="100ms"
		SenderAddr="0x70997970c51812dc3a010c7d01b50e0d17dc79c8"
		[AggOracle.EVMSender.EthTxManager]
				FrequencyToMonitorTxs = "1s"
				WaitTxToBeMined = "2s"
				GetReceiptMaxTime = "250ms"
				GetReceiptWaitInterval = "1s"
				PrivateKeys = [
					{Path = "/app/keystore/aggoracle.keystore", Password = "testonly"},
				]
				ForcedGas = 0
				GasPriceMarginFactor = 1
				MaxGasPriceLimit = 0
				StoragePath = "/tmp/cdk/ethtxmanager-sequencesender.sqlite"
				ReadPendingL1Txs = false
				SafeStatusL1NumberOfBlocks = 5
				FinalizedStatusL1NumberOfBlocks = 10
					[AggOracle.EVMSender.EthTxManager.Etherman]
						URL = "https://rpc.ankr.com/eth_sepolia/578c95407e7831f0ac1ef79cacae294dc9bf8307121ca9fffaf1e556a5cca662"
						MultiGasProvider = false
						L1ChainID = 11155111
						HTTPHeaders = []

[RPC]
Host = "0.0.0.0"
Port = 5576
ReadTimeout = "2s"
WriteTimeout = "2s"
MaxRequestsPerIPAndSecond = 10

[ClaimSponsor]
DBPath = "/tmp/cdk/claimsopnsor.sqlite"
Enabled = true
SenderAddr = "0xfa3b44587990f97ba8b6ba7e230a5f0e95d14b3d"
BridgeAddrL2 = "0xB7098a13a48EcE087d3DA15b2D28eCE0f89819B8"
MaxGas = 200000
RetryAfterErrorPeriod = "1s"
MaxRetryAttemptsAfterError = -1
WaitTxToBeMinedPeriod = "3s"
WaitOnEmptyQueue = "3s"
GasOffset = 0
	[ClaimSponsor.EthTxManager]
		FrequencyToMonitorTxs = "1s"
		WaitTxToBeMined = "2s"
		GetReceiptMaxTime = "250ms"
		GetReceiptWaitInterval = "1s"
		PrivateKeys = [
			{Path = "/app/keystore/claimsopnsor.keystore", Password = "testonly"},
		]
		ForcedGas = 0
		GasPriceMarginFactor = 1
		MaxGasPriceLimit = 0
		StoragePath = "/tmp/cdk/ethtxmanager-claimsponsor.sqlite"
		ReadPendingL1Txs = false
		SafeStatusL1NumberOfBlocks = 5
		FinalizedStatusL1NumberOfBlocks = 10
			[ClaimSponsor.EthTxManager.Etherman]
				URL = "https://rpc.ankr.com/eth_sepolia/578c95407e7831f0ac1ef79cacae294dc9bf8307121ca9fffaf1e556a5cca662"
				MultiGasProvider = false
				L1ChainID = 11155111
				HTTPHeaders = []

[BridgeL1Sync]
DBPath = "/tmp/cdk/bridgel1sync.sqlite"
BlockFinality = "LatestBlock"
InitialBlockNum = 0
BridgeAddr = "{polygonZkEVMBridgeAddress}"
SyncBlockChunkSize = 100
RetryAfterErrorPeriod = "1s"
MaxRetryAttemptsAfterError = -1
WaitForNewBlocksPeriod = "3s"
OriginNetwork=0

[BridgeL2Sync]
DBPath = "/tmp/cdk/bridgel2sync.sqlite"
BlockFinality = "LatestBlock"
InitialBlockNum = 0
BridgeAddr = "{polygonZkEVMBridgeAddress}"
SyncBlockChunkSize = 100
RetryAfterErrorPeriod = "1s"
MaxRetryAttemptsAfterError = -1
WaitForNewBlocksPeriod = "3s"
OriginNetwork=1

[LastGERSync]
# MDBX database path
DBPath = "/tmp/cdk/lastgersync.sqlite"
BlockFinality = "LatestBlock"
InitialBlockNum = 0
GlobalExitRootL2Addr = "{polygonZkEVMGlobalExitRootAddress}"
RetryAfterErrorPeriod = "1s"
MaxRetryAttemptsAfterError = -1
WaitForNewBlocksPeriod = "1s"
DownloadBufferSize = 100

[NetworkConfig.L1]
L1ChainID = 11155111
PolAddr = "0xe223519d64C0A49e7C08303c2220251be6b70e1d"
ZkEVMAddr = "0x45511B6E5FAB7668eA3eCf14e9E9893833392844"
RollupManagerAddr = "0x3ff239788ea041B2FeAEa01F0Fc160103907c1Ef"
GlobalExitRootManagerAddr = "0xcdBDBd809e75123f36c6Eb90845050a02d5C91D9"

[AggSender]
StoragePath = "/tmp/cdk/aggsender.sqlite"
AggLayerURL = ""
AggsenderPrivateKey = {Path = "/pk/sequencer.keystore", Password = "password"}
BlockGetInterval = "2s"
URLRPCL2="http://xlayer-seq:8545"
CheckSettledInterval = "2s"
SaveCertificatesToFiles = false
