[Etherman]
URL = "https://rpc.eu-central-1.gateway.fm/v4/ethereum/non-archival/sepolia?apikey=IkrTRMPAlsjfgTyKz1Xfa5ldS8XSc0PN.En5aU2Gwdxvf3zk2"
ForkIDChunkSize = 200
MultiGasProvider = false
[Etherscan]
ApiKey = ""