datadir: /home/erigon/.local/share/erigon
chain: dynamic-mynetwork
http: true
private.api.addr: localhost:9091
zkevm.l2-chain-id: 195
zkevm.l2-sequencer-rpc-url:
zkevm.l2-datastreamer-url:
zkevm.l1-chain-id: 1337
zkevm.l1-rpc-url: http://zkevm-mock-l1-network:8545

zkevm.address-sequencer: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
zkevm.address-zkevm: "{polygonZkEVMAddress}"
zkevm.address-admin: "{adminAddress}"
zkevm.address-rollup: "{polygonRollupManagerAddress}"
zkevm.address-ger-manager: "{polygonZkEVMGlobalExitRootAddress}"

zkevm.l1-rollup-id: 1
zkevm.l1-first-block: {genesisBlockNumber}
zkevm.l1-block-range: 10
zkevm.l1-query-delay: 100
zkevm.rpc-ratelimit: 300
zkevm.datastream-version: 2

zkevm.executor-urls: ""
zkevm.executor-strict: false
zkevm.witness-full: false
zkevm.l1-contract-address-check: true

zkevm.data-stream-host: "localhost"
zkevm.data-stream-port: 6900
zkevm.default-gas-price: 1
zkevm.max-gas-price: 0
zkevm.gas-price-factor: 0.000001

externalcl: true
http.api: [eth, debug, net, trace, web3, erigon, txpool, zkevm]
http.addr: 0.0.0.0
http.port: 8545
http.vhosts: any
http.corsdomain: any
ws: true

db.read.concurrency: 20000
txpool.globalslots: 100000
txpool.globalbasefeeslots: 100000
txpool.globalqueue: 100000

log.console.verbosity: debug