datadir: /root/.local/share/erigon
chain: dynamic-mynetwork
http: true
private.api.addr: localhost:9091
zkevm.l2-chain-id: 195
zkevm.l2-sequencer-rpc-url: http://zkevm-node:8123
zkevm.l2-datastreamer-url: zkevm-node:6900
zkevm.l1-chain-id: 11155111
zkevm.l1-rpc-url: https://rpc.eu-central-1.gateway.fm/v4/ethereum/non-archival/sepolia?apikey=IkrTRMPAlsjfgTyKz1Xfa5ldS8XSc0PN.En5aU2Gwdxvf3zk2

zkevm.address-sequencer: "0x4820E45eB6Cf99074389544F83FE1F30084bdAb7"
zkevm.address-zkevm: "{polygonZkEVMAddress}"
zkevm.address-admin: "{polygonRollupManagerAddress}"
zkevm.address-rollup: "{polygonZkEVMAddress}"
zkevm.address-ger-manager: "{polygonZkEVMGlobalExitRootAddress}"

zkevm.l1-rollup-id: 1
zkevm.l1-first-block: {genesisBlockNumber}
zkevm.l1-sync-start-block: {genesisBlockNumber}
zkevm.l1-block-range: 10
zkevm.l1-query-delay: 100
zkevm.rpc-ratelimit: 300
zkevm.datastream-version: 2

zkevm.executor-urls: erigon-stateless-executor:50071
zkevm.executor-strict: true
zkevm.witness-full: true

zkevm.sequencer-initial-fork-id: 9
zkevm.data-stream-host: "localhost"
zkevm.data-stream-port: 6900
zkevm.default-gas-price: 1
zkevm.max-gas-price: 0
zkevm.gas-price-factor: 0.000001

externalcl: true
http.api: [eth, debug, net, trace, web3, erigon, txpool, zkevm]
http.addr: 0.0.0.0
http.port: 8545
http.vhosts: any
http.corsdomain: any
ws: true

db.read.concurrency: 20000
txpool.globalslots: 100000
txpool.globalbasefeeslots: 100000
txpool.globalqueue: 100000