[Log]
Level = "debug"
Outputs = ["stdout"]

[SyncDB]
Database = "postgres"
User = "test_user"
Password = "test_password"
Name = "test_db"
Host = "x1-bridge-db"
Port = "5432"
MaxConns = 20
TableSuffix = ""

[ClaimTxManager]
Enabled = true
FreeGas = true
FrequencyToMonitorTxs = "1s"
PrivateKey = {Path = "/pk/keystore.claimtxmanager", Password = "testonly"}
RetryInterval = "1s"
RetryNumber = 10

[Etherman]
L1URL = "http://x1-mock-l1-network:8545"
L2URLs = ["http://x1-json-rpc:8123"]
L1ChainId = 1337
L2ChainIds = [1001]

[Synchronizer]
SyncInterval = "1s"
SyncChunkSize = 100

[BridgeController]
Store = "postgres"
Height = 32

[BridgeServer]
GRPCPort = "9090"
HTTPPort = "8080"
CacheSize = 100000
DefaultPageLimit = 25
MaxPageLimit = 100
BridgeVersion = "v1"
SentinelConfigFilePath = "/app/sentinel_config.json"
    [BridgeServer.DB]
    Database = "postgres"
    User = "test_user"
    Password = "test_password"
    Name = "test_db"
    Host = "x1-bridge-db"
    Port = "5432"
    MaxConns = 20
    TableSuffix = ""
    [BridgeServer.Redis]
    Addr = "x1-bridge-redis:6379"
    Username = ""
    Password = ""
    DB = 0
    MockPrice = true

[CoinKafkaConsumer]
Brokers = ["47.242.254.164:9093","47.242.234.158:9093","8.210.43.30:9093"]
Topics = ["explorer_chainAddressPrice_push"]
ConsumerGroupID = "web3_okbc_explorerchainprice"
InitialOffset = -1
Username = "alikafka_pre_public_intl-sg-25u2gbq160y"
Password = "ON0fCq8vpVnFJKmStqPgRB95sOhDXC0O"
RootCAPath = "/app/root-ca-cert"

[NetworkConfig]
GenBlockNumber = 502 
PolygonBridgeAddress = "0xFc2f92CBFA1b38a4B38B412F582cf08028cBA9e0"
PolygonZkEVMGlobalExitRootAddress = "0xEd236da21Ff62bC7B62608AdB818da49E8549fa7"
L2PolygonBridgeAddresses = ["0xFc2f92CBFA1b38a4B38B412F582cf08028cBA9e0"]
