IsTrustedSequencer = true

[Log]
Environment = "development" # "production" or "development"
Level = "debug"
Outputs = ["stderr"]

[State]
	[State.DB]
	User = "state_user"
	Password = "state_password"
	Name = "state_db"
	Host = "x1-state-db"
	Port = "5432"
	EnableLog = false	
	MaxConns = 200
	[State.Batch]
		[State.Batch.Constraints]
		MaxTxsPerBatch = 300
		MaxBatchBytesSize = 108000 
		MaxCumulativeGasUsed = 1013309916158361 
		MaxKeccakHashes = 1930 
		MaxPoseidonHashes = 227121 
		MaxPoseidonPaddings = 121671 
		MaxMemAligns = 212926 
		MaxArithmetics = 212926 
		MaxBinaries = 425853 
		MaxSteps = 6813484 
		MaxSHA256Hashes = 1436 

[Pool]
FreeClaimGasLimit = 1500000
IntervalToRefreshBlockedAddresses = "5m"
IntervalToRefreshGasPrices = "5s"
MaxTxBytesSize=100132
MaxTxDataBytesSize=100000
DefaultMinGasPriceAllowed = 1000000000
MinAllowedGasPriceInterval = "5m"
PollMinAllowedGasPriceInterval = "15s"
AccountQueue = 64
GlobalQueue = 1024
	[Pool.EffectiveGasPrice]
		Enabled = false
		L1GasPriceFactor = 0.25
		ByteGasCost = 16
		ZeroByteGasCost = 4
		NetProfit = 1
	    BreakEvenFactor = 1.1			
		FinalDeviationPct = 10
		EthTransferGasPrice = 0
		EthTransferL1GasPriceFactor = 0			
		L2GasPriceSuggesterFactor = 0.5
	[Pool.DB]
	User = "pool_user"
	Password = "pool_password"
	Name = "pool_db"
	Host = "x1-pool-db"
	Port = "5432"
	EnableLog = false
	MaxConns = 200

[Etherman]
URL = "https://rpc.ankr.com/eth_sepolia/578c95407e7831f0ac1ef79cacae294dc9bf8307121ca9fffaf1e556a5cca662"
ForkIDChunkSize = 20000
MultiGasProvider = false
	[Etherscan]
		ApiKey = ""

[RPC]
Host = "0.0.0.0"
Port = 8123
ReadTimeout = "60s"
WriteTimeout = "60s"
MaxRequestsPerIPAndSecond = 5000
SequencerNodeURI = ""
EnableL2SuggestedGasPricePolling = true
GasLimitFactor = 1
DisableAPIs = []
	[RPC.WebSockets]
		Enabled = true
		Port = 8133

[Synchronizer]
SyncInterval = "1s"
SyncChunkSize = 100
TrustedSequencerURL = "http://x1-json-rpc:8123" # If it is empty or not specified, then the value is read from the smc.
L1SynchronizationMode = "parallel" # "sequential" or "parallel"
	[Synchronizer.L1ParallelSynchronization]
		MaxClients = 10
		MaxPendingNoProcessedBlocks = 25
		RequestLastBlockPeriod = "5s"
		RequestLastBlockTimeout = "5s"
		RequestLastBlockMaxRetries = 3
		StatisticsPeriod = "5m"
		TimeoutMainLoop = "5m"
		RollupInfoRetriesSpacing= "5s"
		FallbackToSequentialModeOnSynchronized = false
		[Synchronizer.L1ParallelSynchronization.PerformanceWarning]
			AceptableInacctivityTime = "5s"
			ApplyAfterNumRollupReceived = 10

[Sequencer]
DeletePoolTxsL1BlockConfirmations = 100
DeletePoolTxsCheckInterval = "12h"
TxLifetimeCheckInterval = "10m"
TxLifetimeMax = "3h"
LoadPoolTxsCheckInterval = "500ms"
StateConsistencyCheckInterval = "5s"
	[Sequencer.Finalizer]
		NewTxsWaitInterval = "100ms"
		ForcedBatchesTimeout = "5s"
		ForcedBatchesL1BlockConfirmations = 0
		ForcedBatchesCheckInterval = "10s"
		L1InfoTreeL1BlockConfirmations = 0
		L1InfoTreeCheckInterval = "10s"
		BatchMaxDeltaTimestamp = "300s"
		L2BlockMaxDeltaTimestamp = "10s"
		ResourceExhaustedMarginPct = 10
		HaltOnBatchNumber = 0
		SequentialBatchSanityCheck = false
		SequentialProcessL2Block = true
	[Sequencer.StreamServer]
		Port = 6900
		Filename = "/datastreamer/datastream.bin"
		Version = 1
		ChainID = 1337
		Enabled = false

[SequenceSender]
WaitPeriodSendSequence = "65s"
LastBatchVirtualizationTimeMaxWaitPeriod = "60s"
L1BlockTimestampMargin = "5s"
MaxTxSizeForL1 = 131072
MaxBatchesForL1 = 50
SenderAddress = "0x4820E45eB6Cf99074389544F83FE1F30084bdAb7"
L2Coinbase = "0x4820E45eB6Cf99074389544F83FE1F30084bdAb7"
DAPermitApiPrivateKey = {Path = "/pk/sequencer.keystore", Password = "password"}
	[SequenceSender.StreamClient]
		Server = "x1-sequencer:6900"

[Aggregator]
Host = "0.0.0.0"
Port = 50081
RetryTime = "5s"
VerifyProofInterval = "60s"
TxProfitabilityCheckerType = "acceptall"
TxProfitabilityMinReward = "1.1"
ProofStatePollingInterval = "5s"
SenderAddress = "0x694D3f1487e17A96edA98Ced6ae3eC751a08E9Fe"
CleanupLockedProofsInterval = "2m"
GeneratingProofCleanupThreshold = "10m"
UpgradeEtrogBatchNumber = 0

[EthTxManager]
GasPriceMarginFactor = 2
ForcedGas = 0
PrivateKeys = [
	{Path = "/pk/sequencer.keystore", Password = "password"},
	{Path = "/pk/aggregator.keystore", Password = "password"}
]

[L2GasPriceSuggester]
Type = "default"
UpdatePeriod = "10s"
Factor = 0.5
DefaultGasPriceWei = 1000000000
MaxGasPriceWei = 0

[MTClient]
URI  = "x1-executor:50061"

[Executor]
URI = "x1-executor:50071"
MaxGRPCMessageSize = 100000000

[Metrics]
Host = "0.0.0.0"
Port = 9091
Enabled = true
ProfilingHost = "0.0.0.0"
ProfilingPort = 6060
ProfilingEnabled = true

[EventLog]
	[EventLog.DB]
	User = "event_user"
	Password = "event_password"
	Name = "event_db"
	Host = "x1-event-db"
	Port = "5432"
	EnableLog = false
	MaxConns = 200

[HashDB]
User = "prover_user"
Password = "prover_pass"
Name = "prover_db"
Host = "x1-state-db"
Port = "5432"
EnableLog = false
MaxConns = 200
